[package]
name = "rust-jwt-tutorial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonwebtoken = "8"
serde = {version = "1.0", features = ["derive"] }
chrono = "0.4.24"